addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=package-centos-6
  - INSTANCE=package-centos-7
  - INSTANCE=package-debian-8
  - INSTANCE=package-debian-9
  - INSTANCE=package-opensuse-leap
  - INSTANCE=package-ubuntu-1604
  - INSTANCE=package-ubuntu-1804
  - INSTANCE=package-amazonlinux
  - INSTANCE=binary-centos-6
  - INSTANCE=binary-centos-7
  - INSTANCE=binary-debian-8
  - INSTANCE=binary-debian-9
  - INSTANCE=binary-opensuse-leap
  - INSTANCE=binary-ubuntu-1604
  - INSTANCE=binary-ubuntu-1804
  - INSTANCE=binary-amazonlinux

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}
